Update Jenkinsfile.alpine

diff --git a/Jenkinsfile.alpine b/Jenkinsfile.alpine
--- a/Jenkinsfile.alpine
+++ b/Jenkinsfile.alpine
@@ -1,148 +1,132 @@
-@Library('jenkins-shared-libraries') _
+#!/bin/bash
 
-def DISTRIBUTION = 'alpine'
-def IMAGE_NAME = "strongboxci/" + DISTRIBUTION
-def IMAGES = [];
-def SNAPSHOT = params.getOrDefault("DEPLOY", false);
-def TIMESTAMP = System.currentTimeMillis();
+CURRENT_DIR=$(realpath $(dirname "$0"))
+BUILD_WITH_NO_CACHE_ARG=""
+BUILD=$CURRENT_DIR
+MAIN_BUILD_LOG=$CURRENT_DIR/build.log
+TAG_SNAPSHOT=""
+# So that we can pass the timestamp from the CI
+TIMESTAMP=${TIMESTAMP:-`date +%s`}
 
-pipeline {
-    agent {
-        label "alpine-docker"
-    }
-    parameters {
-        booleanParam defaultValue: false, description: 'Deploy tagged images to docker hub.', name: 'DEPLOY'
-    }
-    options {
-        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '50', daysToKeepStr: '', numToKeepStr: '1000')
-        timeout(time: 2, unit: 'HOURS')
-        disableResume()
-        durabilityHint 'PERFORMANCE_OPTIMIZED'
-        disableConcurrentBuilds()
-        skipStagesAfterUnstable()
-    }
-    environment {
-        TIMESTAMP = "$TIMESTAMP"
-    }
-    stages {
-        stage('node') {
-            steps {
-                container("docker") {
-                    nodeInfo("docker")
-                    sh "export"
-                    sh "/bin/bash ${env.WORKSPACE}/build.sh --snapshot --get-snapshot"
-                }
-            }
-        }
-        stage('base') {
-            when {
-                anyOf {
-                    triggeredBy cause: "UserIdCause"
-                    changeset "images/alpine/Dockerfile.${DISTRIBUTION}"
-                }
-            }
-            steps {
-                script {
-                    container("docker") {
-                        def built = processDockerfiles(IMAGE_NAME, SNAPSHOT, "./images/" + DISTRIBUTION + "/Dockerfile." + DISTRIBUTION);
-                        IMAGES.plus(built)
-                    }
-                }
-            }
-        }
-        stage('jdk8') {
-            when {
-                anyOf {
-                    // should run upon manual build.
-                    triggeredBy cause: "UserIdCause"
-                    changeset "images/${DISTRIBUTION}/Dockerfile.${DISTRIBUTION}"
-                    changeset "images/${DISTRIBUTION}/jdk8/Dockerfile.${DISTRIBUTION}.*"
-                }
-            }
-            steps {
-                container("docker") {
-                    script {
-                        def files = sh(returnStdout: true, script: '''find ./images/${DISTRIBUTION}/jdk8 -type f -name "*Dockerfile*" | sort | xargs''')
-                        def built = processDockerfiles(IMAGE_NAME, SNAPSHOT, files)
-                        IMAGES.plus(built)
-                    }
-                }
-            }
-        }
-        stage('jdk11') {
-            when {
-                anyOf {
-                    // should run upon manual build.
-                    triggeredBy cause: "UserIdCause"
-                    changeset "images/${DISTRIBUTION}/Dockerfile.${DISTRIBUTION}"
-                    changeset "images/${DISTRIBUTION}/jdk11/Dockerfile.${DISTRIBUTION}.*"
-                }
-            }
-            steps {
-                container("docker") {
-                    script {
-                        def files = sh(returnStdout: true, script: '''find ./images/${DISTRIBUTION}/jdk11 -type f -name "*Dockerfile*" | sort | xargs''')
-                        processDockerfiles(IMAGE_NAME, SNAPSHOT, files)
-                    }
-                }
-            }
-        }
-        stage('publishing') {
-            when {
-                anyOf {
-                    branch 'master'
-                    expression { params.getOrDefault("DEPLOY", false) == true }
-                }
-            }
-            steps {
-                container("docker") {
-                    echo "Deploying images: " + IMAGES.toString()
-                    sh "/bin/bash ${env.WORKSPACE}/build.sh --snapshot --get-snapshot"
-/*
-                    withDockerRegistry([credentialsId: dockerCredentials, url: dockerUrl]) {
-                        script {
-                            IMAGES.each {
-                                sh label: "Publishing ${it}...",
-                                   script: "docker push ${it}"
-                            }
-                        }
-                    }
-*/
-                }
-            }
-        }
-    }
+build() {
+  DOCKER_FILE=$1
+
+  echo "=== Building $DOCKER_FILE"
+  echo ""
+
+  BASEPATH=`dirname $DOCKER_FILE`
+  FILENAME=`basename $DOCKER_FILE`
+  DISTRIBUTION=`echo $FILENAME | awk -F[=.] '{print $2}'`
+  TAG=`echo $FILENAME | awk -F "Dockerfile.$DISTRIBUTION." '{print $2}'`
+  if [[ -z $TAG ]]; then
+    TAG="base"
+  fi
+
+  if [[ ! -z "$TAG_SNAPSHOT" ]]; then
+    TAG="$TAG-$TAG_SNAPSHOT"
+  fi
+
+  IMAGE="strongboxci/$DISTRIBUTION:$TAG"
+
+  echo "Distribution: $DISTRIBUTION"
+  echo "Tag: $TAG"
+  echo "Image: $IMAGE"
+  echo ""
+
+  (set -euxo pipefail; docker build -f "$DOCKER_FILE" -t "$IMAGE" $BUILD_WITH_NO_CACHE_ARG $CURRENT_DIR | tee "$DOCKER_FILE.build.log") || {
+    echo "fail: $IMAGE" >> $MAIN_BUILD_LOG
+    echo "Done" >> $MAIN_BUILD_LOG
+    exit 1
+  }
+
+  echo ""
+
+  echo "success: $IMAGE" >> $MAIN_BUILD_LOG
 }
 
-def processDockerfiles(NAME, SNAPSHOT, files)
-{
-    if (files instanceof List)
-    {
-        def BUILD_ARGS = SNAPSHOT ? " --snapshot " : ""
-        files.split(" ").each {
-            println it
-            def match = (it =~ /(.*)\\/Dockerfile\.(\w+)(\.(.+))?/)
-            if (match.find())
-            {
-                // DO NOT USE THIS, BECAUSE IT FAILS WITH `"docker build" requires exactly 1 argument.` - LIKELY A BUG!
-                // docker.build(IMAGE, '-f ' + it + ' --no-cache .')
+usage() {
+  cat <<EOF
 
-                def TAG = match.group(4) ? match.group(4) : 'base'
-                def IMAGE = NAME + ":" + TAG
+ $0 [options] path
 
-                sh label: "Building $IMAGE",
-                   script: "/bin/bash ${env.WORKSPACE}/build.sh ${BUILD_ARGS} $it"
+  path:
+    is not specified  - will build all Dockerfiles under ./images/
+    is a directory    - will build all Dockerfiles in that path
+    is a file         - will build that Dockerfile.
 
-                IMAGES.add(IMAGE)
-            }
+  Options:
+    -h |--help          Prints this help message.
+    -c |--clear         Clears all temp/log files from the repository.
+    -nc|--no-cache      Adds --no-cache to the docker build command
+    -s |--snapshot      Tag the images as snapshots (i.e. strongboxci/alpine:base-TIMESTAMP)
+    -gs|--get-snapshot  Prints the snapshot version (i.e. TIMESTAMP || PR-123-TIMESTAMP || BRANCH-TIMESTAMP; needed for CI)
+
+EOF
+    exit 0
+}
+
+clearLogs() {
+    (set -ex; find . -type f -name "*.log" -exec rm -rfv {} \;)
+    exit 0
+}
+
+while [[ $# -gt 0 ]]; do
+    key="$1"
+    case $key in
+        -c|--clear)
+            clearLogs
+            exit 0
+        ;;
+        -nc|--no-cache)
+            BUILD_WITH_NO_CACHE_ARG=" --no-cache "
+            shift 1
+        ;;
+        -s|--snapshot)
+            # Jenkins PR/Branch env
+            if [[ ! -z "$CHANGE_ID" ]]; then
+              TAG_SNAPSHOT="PR-$CHANGE_ID-$TIMESTAMP"
+            elif [[ ! -z "$BRANCH_NAME" ]]; then
+              TAG_SNAPSHOT="$BRANCH_NAME-$TIMESTAMP"
             else
-            {
-                println "Something went wrong and we could not properly parse ${it} - skipping"
-            }
-        }
-    }
-    else
-    {
-        error "processDockerfiles expects argument to be an array, but received " + files.getClass()
-    }
-}
+              TAG_SNAPSHOT="$TIMESTAMP"
+            fi
+            shift
+          ;;
+        -gs|--get-snapshot)
+          echo $TAG_SNAPSHOT
+          exit 0
+        ;;
+        -h|--help)
+            usage
+            exit 0
+        ;;
+        *)
+            BUILD=$1
+            shift
+            break
+        ;;
+    esac
+done
+
+if [[ ! -z $BUILD ]]; then
+  # Clear main build log before starting.
+  truncate -s 0 $MAIN_BUILD_LOG
+
+  # build all Dockerfiles in a directory
+  if [[ -d $BUILD ]]; then
+    for dockerFile in $(find $BUILD -type f -name "*Dockerfile*" ! -name "*.log" ! -name "*.bkp*" | sort | xargs); do
+      build "$dockerFile"
+    done
+    echo "Done" >> $MAIN_BUILD_LOG
+  # build a specific Dockerfile
+  elif [[ -f $BUILD ]]; then
+    build "$BUILD"
+    echo "Done" >> $MAIN_BUILD_LOG
+  # what just happened?
+  else
+    echo "$1 is neither a file nor a directory. Exiting."
+    exit 1
+  fi
+fi
+
+echo ""
